export const options = [
  "Walcz",
  "Przemyśl to",
  "Walnij piwerko",
  "Odwiedź przyjaciela",
  "Przeczytaj książkę",
  "Idź na spacer",
  "Posłuchaj muzyki",
  "Idź na siłownię",
  "Zadzwoń do rodziny",
  "Ugotuj kolację",
  "Spróbuj medytacji",
  "Oglądnij film",
  "Zrób zakupy",
  "Idź na rower",
  "Zajrzyj do kalendarza",
  "Sprzątnij mieszkanie",
  "Napisz list",
  "Stworz plan",
  "Przemyśl finanse",
  "Naucz się czegoś nowego",
  "Przejrzyj zdjęcia",
  "Idź na pływalnię",
  "Zrób coś kreatywnego",
  "Posprzątaj komputer",
  "Napisz do starego znajomego",
  "Zapisz się na kurs",
  "Zorganizuj spotkanie",
  "Spróbuj nowego hobby",
  "Zrób krótką drzemkę",
  "Przemyśl swoje cele",
  "Odwiedź miejsce, w którym jeszcze nie byłeś",
  "Idź na masaż",
  "Zrób przerwę",
  "Idź na koncert",
  "Zorganizuj imprezę",
  "Zaplanuj wakacje",
  "Idź na randkę",
  "Zrób sobie dzień wolny",
  "Zaplanuj swoją przyszłość",
  "Przytul kogoś",
];
